version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: gpt4_auth_user
      POSTGRES_USER: gpt4_auth_user
      POSTGRES_DB: gpt4_auth_schema
    #    ports:
    #      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  auth:
    build:
      context: .
      dockerfile_inline: |
        FROM python:latest
        
        RUN mkdir /app
        COPY . /app/
        RUN pip install --no-cache-dir -r /app/requirements.txt
        
        CMD [ "python", "/app/manage.py", "runserver" ]
    restart: always
    command: bash -c "sleep 7; python3 /app/manage.py makemigrations; python3 /app/manage.py migrate; python3 /app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: "OPENAI_API_KEY"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"